from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
ASSETS_DIR = PROJECT_ROOT / 'assets'
TEMPLATES_DIR = ASSETS_DIR / 'templates'
OUTPUT_DIR = PROJECT_ROOT / 'output'

WARP_SIZE = 900
CELL_INNER_MARGIN = 12
NORMALIZED_GLYPH_SIZE = 64
OCR_MSE_THRESHOLD = 0.035
OCR_MARGIN_THRESHOLD = 0.003
OCR_CORR_THRESHOLD = 0.78
GRID_DETECTION_MIN_AREA = 50_000
DRAW_COLOR_BGR = (36, 155, 86)
DRAW_FONT_SCALE = 1.7
DRAW_THICKNESS = 3
